gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 1209600
  firewall: api
  user_provider: security.user.provider.concrete.app_user_provider
  token_parameter_name: refresh_token
  single_use: false
  manager_type: orm