nelmio_cors:
  defaults:
    allow_credentials: true
  paths:
    '^/api/':
      allow_origin: ['http://localhost:3000']
      allow_headers: ['Content-Type','X-Requested-With']
      allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
      max_age: 3600 