# config/packages/security.yaml
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email         

  role_hierarchy:
    ROLE_USER: ['ROLE_STUDENT', 'ROLE_PROFESSOR']

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login_check    
        username_path: username     
        password_path: password 
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~                             

  access_control:
    - { path: ^/api, roles: PUBLIC_ACCESS, methods: [OPTIONS] }

    # routes publiques d'auth
    - { path: ^/api/login_check$,  roles: PUBLIC_ACCESS }
    - { path: ^/api/token/refresh$, roles: PUBLIC_ACCESS }
    - { path: ^/api/auth/logout$,  roles: PUBLIC_ACCESS }

    # routes par rôle
    - { path: ^/api/student$,   roles: ROLE_STUDENT }
    - { path: ^/api/professor$, roles: ROLE_PROFESSOR }

    # le reste de l’API
    - { path: ^/api/me$, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api,     roles: IS_AUTHENTICATED_FULLY }
