# Utilise l'image PHP avec FPM
FROM php:8.2-fpm

# Installer les dépendances système utiles pour Symfony + extensions PHP (MySQL + PostgreSQL)
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libpq-dev \
    libzip-dev \
    zip \
    libonig-dev \
    libxml2-dev \
    default-mysql-client \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql zip

# Copier Composer depuis l'image officielle
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/html

# Copier les fichiers du projet dans le répertoire de travail
COPY . .

# Marquer ce dossier comme sûr (évite les erreurs Git)
RUN git config --global --add safe.directory /var/www/html

# Installer les dépendances (sans dev, sans scripts auto)
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-scripts

# Donner les permissions adéquates
RUN chown -R www-data:www-data /var/www/html

# Exposer le port PHP-FPM (utilisé par NGINX en reverse proxy)
EXPOSE 9000

# Lancer PHP-FPM en mode foreground
CMD ["php-fpm"]