# Utilise l'image PHP avec FPM
FROM php:8.2-fpm

# Installer les dépendances système utiles pour Symfony + extensions PHP (MySQL + PostgreSQL)
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libpq-dev \
    libzip-dev \
    zip \
    libonig-dev \
    libxml2-dev \
    default-mysql-client \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql zip

# Copier Composer depuis l'image officielle
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/html

# Copier les fichiers du projet dans le répertoire de travail
COPY . .

# Déclare le dossier comme sûr pour Git (évite le warning fatal)
RUN git config --global --add safe.directory /var/www/html

# Installer les dépendances SANS les dev et SANS exécuter les scripts (pour éviter MakerBundle, Fixtures, etc.)
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-scripts

# Donner les permissions adéquates
RUN chown -R www-data:www-data /var/www/html

# Exposer le port utilisé par php-fpm
EXPOSE 9000

# Commande par défaut pour démarrer php-fpm
CMD ["php-fpm"]