nelmio_cors:
  defaults:
    allow_origin: ['https://uni-connect.cloud/']
    allow_credentials: true
    allow_headers: ['Content-Type','Authorization','X-Requested-With']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    max_age: 3600
  paths:
    '^/api/': ~
