name: Symfony Backend CI/CD

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: phpunit
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql
          tools: composer
      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
          extensions: intl, mbstring, pdo_sqlite
          tools: composer

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare test database (MySQL)
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/app_test
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
      - name: Run PHPUnit
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/app_test
        run: ./vendor/bin/phpunit --testdox --log-junit var/junit.xml --coverage-clover var/coverage.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-reports
          path: |
            var/junit.xml
            var/coverage.xml


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push avec tags en dur selon la branche
      - name: Build & push (main → prod/latest)
        if: github.ref == 'refs/heads/main'
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker build -t inesbrm1/uniconnect-backend:prod -t inesbrm1/uniconnect-backend:latest -t inesbrm1/uniconnect-backend:${SHORT_SHA} .
          docker push inesbrm1/uniconnect-backend:prod
          docker push inesbrm1/uniconnect-backend:latest
          docker push inesbrm1/uniconnect-backend:${SHORT_SHA}
      - name: Build & push (dev → preprod/dev-latest)
        if: github.ref == 'refs/heads/dev'
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker build -t inesbrm1/uniconnect-backend:preprod -t inesbrm1/uniconnect-backend:dev-latest -t inesbrm1/uniconnect-backend:${SHORT_SHA} .
          docker push inesbrm1/uniconnect-backend:preprod
          docker push inesbrm1/uniconnect-backend:dev-latest
          docker push inesbrm1/uniconnect-backend:${SHORT_SHA}
      # Déploiement avec tags explicites (pas de variables passées)
      - name: Deploy PROD (main)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            cd /var/www
            docker pull inesbrm1/uniconnect-backend:prod
            docker compose up -d --no-deps --build backend
      - name: Deploy PREPROD (dev)
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            cd /var/www
            docker pull inesbrm1/uniconnect-backend:preprod
            docker compose up -d --no-deps --build backend-preprod
